name: CI workflow

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      # - name: Start
      #   run: npm run start
      # - name: Test
      #   run: npm run test

